spring:
  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:/data/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false

management:
  endpoints:
    web:
      cors:
        allow-origin: http://localhost:3000
        allow-methods: GET, POST, DELETE, PUT





