package com.dtcc.hospital.hm.category;

public enum ProgramClassification {
    DEPARTMENT_PEDIATRIC,
    DEPARTMENT_ONCOLOGY,
    DEPARTMENT_ORTHOPAEDIC,
    DEPARTMENT_CARDIO,
    DEPARTMENT_NEUROLOGY,
    DEPARTMENT_SURGERY,
    DEPARTMENT_DERMATOLOGY,
    DEPARTMENT_DIAGNOSTICS,
    PREVENTION,
    EPIDEMIC,
    ELDERLY_CARE,
    OTHER_DISEASE

}
